# Generated by Django 4.2 on 2023-05-01 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import memberships.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_period', models.CharField(blank=True, choices=[('Month', 'Month'), ('Year', 'Year'), ('Custom', 'Custom')], max_length=200, null=True)),
                ('number_of_words', models.PositiveBigIntegerField(default=0, verbose_name='number of words')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stripe_plan_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=40)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('user_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.usermembership')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.ForeignKey(default=memberships.models.MembershipChoices.free_membership, on_delete=django.db.models.deletion.SET_DEFAULT, to='memberships.membershipchoices', to_field='name', verbose_name='Membership type'),
        ),
    ]
