# Generated by Django 4.1.2 on 2022-11-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_subscription_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='members',
        ),
    ]
