# Generated by Django 4.1.2 on 2022-12-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_remove_subscription_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_period',
            field=models.CharField(blank=True, choices=[('Monthly', 'Month'), ('Annualy', 'Year'), ('Custom', 'Custom')], max_length=200, null=True),
        ),
    ]
