# Generated by Django 4.1.2 on 2023-02-17 21:47

from django.db import migrations, models
import django.db.models.deletion
import memberships.models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_alter_membership_membership_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.ForeignKey(default=memberships.models.MembershipChoices.free_membership, on_delete=django.db.models.deletion.SET_DEFAULT, to='memberships.membershipchoices', to_field='name', verbose_name='Membership type'),
        ),
    ]
