# Generated by Django 4.1.7 on 2023-02-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_period',
            field=models.CharField(blank=True, choices=[('Month', 'Month'), ('Year', 'Year'), ('Custom', 'Custom')], max_length=200, null=True),
        ),
    ]
