# Generated by Django 4.1.7 on 2023-02-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_subscription_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
