# Generated by Django 4.1.7 on 2023-02-21 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_subscription_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='test',
        ),
    ]
