# Generated by Django 4.2 on 2023-09-29 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_ai.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_language', models.CharField(max_length=225, unique=True, verbose_name='output language')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='template category')),
            ],
            options={
                'verbose_name_plural': 'Template Categories',
            },
        ),
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone_type', models.CharField(max_length=225, unique=True, verbose_name='Tone')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True, verbose_name='template name')),
                ('description', models.TextField(blank=True, verbose_name='template description')),
                ('prompt', models.TextField(blank=True, default='Generate me a  {user_template_name} for my product or brand named {product_name}.\n-With these features :{user_product_description}.\n-In this Language: {output_language}.\n-with this tone: {tone}.', verbose_name='template prompt')),
                ('max_token', models.PositiveIntegerField(blank=True, default=255, verbose_name='max token')),
                ('temperature', models.FloatField(default=0.7)),
                ('frequency_penalty', models.FloatField(default=0.0)),
                ('model', models.CharField(blank=True, default='text-davinci-003', max_length=100)),
                ('product_name_label', models.CharField(blank=True, default='Your Product Name Here', max_length=150)),
                ('product_name_placeholder', models.CharField(blank=True, default='Print.ai', max_length=125)),
                ('user_description_label', models.CharField(blank=True, default='Provide Some description for your product :', max_length=300)),
                ('user_description_placeholder', models.TextField(blank=True, default='Best AI copy writing app to make it easier !')),
                ('is_published', models.BooleanField(default=False)),
                ('is_product_name_required', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_ai.templatecategory', verbose_name='template category')),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=250, verbose_name='Project Name')),
                ('product_name', models.CharField(blank=True, max_length=250, verbose_name='Product Name')),
                ('user_description', models.TextField(blank=True, max_length=1000, verbose_name='user description')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('output_language', models.ForeignKey(default=my_ai.models.Language.get_default_language, on_delete=django.db.models.deletion.SET_DEFAULT, to='my_ai.language', to_field='output_language', verbose_name='output language')),
                ('template_name', models.ForeignKey(default=my_ai.models.Templates.get_default_template, on_delete=django.db.models.deletion.SET_DEFAULT, to='my_ai.templates', to_field='name', verbose_name='template name')),
                ('tone', models.ForeignKey(default=my_ai.models.Tone.get_default_tone, on_delete=django.db.models.deletion.SET_DEFAULT, to='my_ai.tone', to_field='tone_type', verbose_name='tone_type')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='AiDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_answer', models.TextField(blank=True, null=True, verbose_name='ai_product_description')),
                ('template_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ai_product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_ai.productdescriptionmodel', verbose_name='ai_product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
