# Generated by Django 4.1.7 on 2023-02-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='frequency_penalty',
            field=models.FloatField(default=0.0),
        ),
    ]
