# Generated by Django 4.1.7 on 2023-02-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ai', '0002_templates_frequency_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
