# Generated by Django 4.1.7 on 2023-02-22 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ai', '0003_templates_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='test',
        ),
    ]
