# Generated by Django 4.1.7 on 2023-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ai', '0004_remove_templates_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='icon_class',
        ),
        migrations.AlterField(
            model_name='templates',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
    ]
